### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by thetekst** [Bashka/vim_plugmanager#1]
Добрый день.
Понравились ваши последние статьи на хабре про vim.
Я новичек, хотел бы начать использовать его.
Из первой статьи установил vim_lib, но вот с установкой vim_plugmanager возникли проблемы.
В мане у вас написано:
Плагин устанавливается аналогично другим плагинам редактора Vim.

Выполнил: 
git clone https://github.com/Bashka/vim_plugmanager.git ~/.vim/bundle/vim_plugmanager

Дальше я так понял нужно его в .vimrc прописать.
Не подскажите как?

**Comment by Bashka** [comment]
Что у вас в данный момент в .vimrc?

**Comment by thetekst** [comment]
filetype off 
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle') " Адрес до вашего ~/.vim/bundle

Plugin 'vim_lib'
" Другие плагины

filetype indent plugin on

**Comment by Bashka** [comment]
Вот перед комментарием "Другие плагины" добавьте запись:
Plugin 'vim_plugmanager'

**Comment by Bashka** [comment]
Я посоветую вам реализовать это чуть иначе. Создайте файл ~/.vim/plugins.vim и в него добавьте:
Plugin 'vim_lib'
Plugin 'vim_plugmanager'
А в .vimrc поменяйте содержимое на такое:
filetype off  
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle')
so ~/.vim/plugins.vim
filetype indent plugin on

Тем самым вы разделите файл .vimrc и объявления плагинов. Все новые плагины вы будете добавлять в ~/.vim/plugins.vim в виде Plugin 'имя'

**Comment by thetekst** [comment]
Сделал как вы и посоветовали. 
Набрал PlugmanagerList, открылся список.
Сейчас посмотрю, что можно поставить для первого раза.
Спасибо большое за отзывчивость =)

**Comment by Bashka** [comment]
Пожалуйста.
Подыщите любой плагин на GitHub и укажите его логин/имя (на пример Bashka/vim_start). После установки плагина, в файл ~/.vim/plugins.vim будет автоматически добавлена запись Plugin 'имяПлагина'

**Comment by thetekst** [comment]
Здорово, работает! Еще раз спасибо
