### ISSUE TITLE
Не могу подключить плагин к отдельному проекту

### ISSUE THREAD

**Issue by gBopHuk** [Bashka/vim_plugmanager#2]
Выполнил :
1)VimPrjCreate 
2)Затем через vim_plugmanager установил плагин https://github.com/Shougo/neocomplete.vim 
3)Встало в каталог Project/.vim/bundle/neocomplete/
4)Запись о плагине появилась в Project/.vim/plugins.vim

Но при старте проекта плагин не подхватывается, проверял из командой строки наличие :NeoCompleteEnable

**Comment by Bashka** [comment]
Можете показать содержание файла Project/.vimrc и Project/.vim/plugins.vim?

**Comment by gBopHuk** [comment]
$ cat .vimrc 
filetype off
call vim_lib#sys#Autoload#init('.vim', 'bundle')
so .vim/plugins.vim
filetype indent plugin on

$ cat .vim/plugins.vim
Plugin 'neocomplete'

**Comment by Bashka** [comment]
Проверил у себя в новом проекте. Все работает. Возможно дело в том, что после установки плагина в каталог проекта вы не перезапустили Vim. vim_plugmanager не запускает установленные плагины после установки, необходимо перезапустить Vim для этого проекта.

**Comment by Bashka** [comment]
Заметил вот еще что. При установке neocomplete.vim с использованием vim_plugmanager у вас должен появится каталог Project/.vim/bundle/neocomplete.vim, а в Project/.vim/plugins.vim должна появится запись: Plugin 'neocomplete.vim'

Если сравнивать с вашим листингом, то у вас в plugins.vim неверное имя плагина (не neocomplete, а neocomplete.vim), так как vim_plugmanager копирует имя плагина из репозитория.

**Comment by gBopHuk** [comment]
> ... так как vim_plugmanager копирует имя плагина из репозитория.

Что нужно делать в таких случаях ? И как избежать таких случаев?

Сделал измениния 
$ cat .vim/plugins.vim
Plugin 'neocomplete.vim'

Перезапустил vim 

Результат такой же - плагин не работает.

Можете написать алгоритм ваших действий при установке neocomplete в проект?

**Comment by gBopHuk** [comment]
Выполнил заново все действия из первого сообщения.
Теперь всё завелось.
Что было не так в прошлый раз не знаю. Может дело было всё в той же "set secure" в .vimrc. Надо проверить.

Провёл исследование 
Добавил через vim_plugmanager два плагина
 https://github.com/Shougo/neocomplete.vim
 https://github.com/Shougo/neocomplete
Оба плагина установились в bundle
$ ls -l .vim/bundle/
итого 8
drwxr-xr-x 7 4294967294 4294967294 4096 июл 29 11:44 neocomplete
drwxr-xr-x 7 4294967294 4294967294 4096 июл 29 11:39 neocomplete.vim

$ cat .vim/plugins.vim
"Plugin 'neocomplete.vim'
Plugin 'neocomplete'

Поочередно комминтируя и перезапуская vim пришёл к выводу, что оба варианта добавления рабочие

**Comment by Bashka** [comment]
Не могу знать, что было не так у вас. Действую в три шага:
1. Открываю окно vim_plugmanager
2. Нажимаю 'a' и указываю репозиторий нового плагина
3. Перезапускаю проект
После все работает.
