### ISSUE TITLE
Плагин Airline для основного каталога ~/.vim 

### ISSUE THREAD

**Issue by gBopHuk** [Bashka/vim_plugmanager#3]
Попытался установить плагин  airline bling/vim-airline.git как плагин по-умолчанию
$vim
1) :PlugmanagerList
2) Нажимаем клавишу a bling/vim-airline.git
Плагин качается появляется в pluginlist
3) Выходим из vim
4) Запускаем vim

Плагина не работает и пропал из Pluginmanagerlist

Что-то опят упускаю?

**Comment by Bashka** [comment]
Возможно упускаете. Проверил у себя следующим образом:
1. :PlugmanagerList
2. Нажимаю 'a' и ввожу 'bling/vim-airline' (без .git в конце), то есть имя автора и имя плагина через слеш
3. Проверяю ~/.vim/bundle, плагин там появился, появился он же и в конце файла ~/.vim/plugins.vim
4. Проверяю дееспособность, все работает

**Comment by gBopHuk** [comment]
Попробовал без .git

$cat ~/.vim/plugins.vim 
Plugin 'vim_start.git'
Plugin 'vim-airline'

$ ls ~/.vim/bundle/
vim-airline
vim_lib
vim_plugmanager
vim_prj
vim_start

**Comment by gBopHuk** [comment]
" Plugins list (Press ? for help) "                                                                                                                          

" ~/.vim
vim_lib
vim_plugmanager
vim_prj
vim_start

**Comment by Bashka** [comment]
Пожалуйста, попробуйте сделать следующее:
1. Откройте Vim
2. Выполните команду :echo vim_lib#sys#Autoload#getLevels()
3. Сообщите мне о результате
Метод vim_lib#sys#Autoload#getLevels возвращает массив доступных для инициализации плагинов Vim.

Аналогично vim-airline, плагин vim_start нужно устанавливать без .git вконце.
Так же попробуйте заменить содержимое файла ~/.vim/plugins.vim на следующее:
Plugin 'vim_lib'
Plugin 'vim_plugmanager'
Plugin 'vim_prj'
Plugin 'vim_start'
Plugin 'vim-airline'

**Comment by gBopHuk** [comment]
2) :echo vim_lib#sys#Autoload#getLevels()
{'~/.vim': {'plugins': ['vim_lib', 'vim_plugmanager', 'vim_prj', 'vim_start'], 'plugdir': 'bundle'}}

Вывод этой же команды после переустановки плагина vim_start и правки plugins.vim
{'~/.vim': {'plugins': ['vim_lib', 'vim_plugmanager', 'vim_prj', 'vim_start'], 'plugdir': 'bundle'}}

$ cat ~/.vim/plugins.vim
Plugin 'vim_lib'
Plugin 'vim_plugmanager'
Plugin 'vim_prj'
Plugin 'vim-airline'
Plugin 'vim_start'

**Comment by Bashka** [comment]
Плагин vim-airline у вас отсутствует в vim_lib#sys#Autoload#getLevels(). Это возможно только в двух случаях:
1. Если плагин не объявлен в plugins.vim (не ваш случай, так как он объявлен в этом файле)
2. Каталога плагина нет в .vim/bundle (судя по вашему второму комментарию, он у вас есть)
К сожалению не могу повторить эту проблему у себя локально.

**Comment by gBopHuk** [comment]
Решил всё проверить на чистой машине в vbox .
Cоздал каталог ~/.vim/bundle
Cклонировал туда репозитории vim_lib и vim_plugmanager

$cat ~/.vimrc
colorscheme elflord

filetype off 
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle') " Адрес до вашего ~/.vim/bundle

Plugin 'vim_lib'
Plugin 'vim_plugmanager'
" Другие плагины
"
filetype indent plugin on
$ ls  ~/.vim
bundle

Файла ~/.vim/plugins.vim пока нету

1) Запускаю vim
2) Ввожу :PluginmanagerList
3) нажимаю "a", затем вставляю bling/vim-airline
4) клонирует репозиторий в ~/.vim/bundle/vim-airline
5) ругается на то что нету файла ~/.vim/plugins.vim, но создаёт его и добавляет  Plugin 'vim-airline'
6) 'vim-airline' появился в :PluginmanagerList
7) нажимаем :q и выходим из vim
8) запускаем vim 
9) Плагин airline не подхватился и пропал из :PluginmanagerList

Сотояние файлов 
$ls -R ~/.vim

/home/guest/.vim:
bundle  plugins.vim

/home/guest/.vim/bundle:
vim-airline  vim_lib  vim_plugmanager

$ cat  ~/.vimrc
colorscheme elflord

filetype off 
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle') " Адрес до вашего ~/.vim/bundle

Plugin 'vim_lib'
Plugin 'vim_plugmanager'
" Другие плагины
"
filetype indent plugin on

$ cat ~/.vim/plugins.vim 
Plugin 'vim-airline'

**Comment by Bashka** [comment]
Добавьте в .vimrc перед "filetype indent plugin on" запись: so ~/.vim/plugins.vim - у вас должно получится так:
colorscheme elflord

filetype off
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle') " Адрес до вашего ~/.vim/bundle

Plugin 'vim_lib'
Plugin 'vim_plugmanager'
" Другие плагины
so ~/.vim/plugins.vim
filetype indent plugin on

**Comment by gBopHuk** [comment]
Спасибо - взлетело =)
Только сейчас начал понимать структуру.

**Comment by Bashka** [comment]
Структура очень простая. Есть системная переменная runtimepath, которая определяет каталоги, в которых Vim следует искать плагины и другие скрипты. Для того, чтобы устанавливаемые плагины работали, каталоги, в которые они копируются (на пример ~/.vim/bundle/vim-airline) должны быть добавлены в runtimepath. Сделать это можно руками добавив их в файле .vimrc:
let &rtp = '~/.vim/bundle/vim-airline'
А можно с помощью vim_lib, которая определяет команду Plugin, которая делает тоже самое + еще некоторые настройки для корректной работы всего этого зоопарка.
Плагин vim_plugmanager при установки стороннего плагина делает 2 вещи:
1. Копирует сторонний плагин в ~/.vim/bundle/имяПлагина
2. Добавляет имяПлагина в ~/.vim/plugins.vim в виде команды Plugin 'имяПлагина'
То есть все действия автоматизируются.
Я использую файл ~/.vim/plugins.vim для того, чтобы не мусорить в .vimrc. Я просто подключаю этот файл в .vimrc с помощью команды:
so ~/.vim/plugins.vim
что автоматически подключает все перечисленные в нем плагины.
Звучит запутанно, но на деле это очень просто.
