### ISSUE TITLE
Установка solarized темы

### ISSUE THREAD

**Issue by dar1ock** [Bashka/vim_plugmanager#4]
Добрый день,
потихоньку разбираюсь с плагинами, 
но никак не могу победить установку цветов solarized

ставил через Plugmanager
в ~/.vim/Plugins.vim появилась строка Plugin 'vim-colors-solarized'
в ~/.vim.rc добавляю colorsheme solarized
и при перезапуске получаю ошибку что тема не найдена

**Comment by Bashka** [comment]
Файл ~/.vim.rc должен называться ~/.vimrc (без расширения).
Покажите содержимое вашего .vimrc файла.

**Comment by dar1ock** [comment]
"set exrc
"set secure

"docs
"helptags ~/.vim/doc
"helptags ~/.vim/bundle/vim_prj/doc
"helptags ~/.vim/bundle/vim_plugmanager/doc

"some settings
set fencs=utf-8,cp1251,koi8-r,cp866
set laststatus=2
set cursorline

set cursorcolumn
set noshowmode

"Airline settings
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#enable#fugitive=1
let g:airline#enable#syntastic=1
let g:airline#enable#bufferline=1
let g:airline_theme='solarized'

"Nerdtree settings
nmap :NERDTreeToggle
let g:NERDTreeChDirMode = 2
let g:NERDTreeShowBookmarks = 1

"ReadOnly check
function CheckRo()
if &readonly
nmap :q
endif
endfunction
au BufReadPost \* call CheckRo()

filetype off 
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle') " Адрес до вашего ~/.vim/bundle
so ~/.vim/plugins.vim
filetype indent plugin on

syntax enable
set background=dark
colorscheme solarized

**Comment by Bashka** [comment]
Проверьте следующее:
1. Есть ли у вас каталог ~/.vim/bundle/vim-colors-solarized/
2. Есть ли у вас файл ~/.vim/plugins.vim (обратите внимание что все буквы в нижнем регистре)

**Comment by dar1ock** [comment]
ls ~/.vim/bundle/vim-colors-solarized/
autoload  bitmaps  colors  doc  README.mkd

ls ~/.vim
bundle  doc  plugins.vim

cat ~/.vim/plugins.vim 

Plugin 'vim_lib'
Plugin 'vim_plugmanager'
Plugin 'vim_prj'
Plugin 'vim_start'
Plugin 'vim_template'
Plugin 'vim_start'
Plugin 'vim_write'
Plugin 'vim_winmanager'
Plugin 'vim_git'
Plugin 'vim-airline'
Plugin 'nerdtree'
Plugin 'vim-colors-solarized'

**Comment by Bashka** [comment]
Сделайте следующее. Откройте редактор Vim и выполните команду
:echo vim_lib#sys#Autoload#levels
покажите результат

**Comment by dar1ock** [comment]
{'~/.vim': {'plugins': ['vim_lib', 'vim_plugmanager', 'vim_prj', 'vim_start', 'vim_template', 'vim_start', 'vim_write', 'vim_winmanager', 'vim_git', '
vim-airline', 'nerdtree', 'vim-colors-solarized', 'vim-gitgutter'], 'plugdir': 'bundle'}}

**Comment by Bashka** [comment]
Судя по результату, плагин vim-colors-solarized подключен. Возможно проблема не в строке:
colorscheme solarized
которая подключает цветовую схему для редактора, а в строке:
let g:airline_theme='solarized'
которая подключает цветовую схему для airline (возможно она у вас отсутствует). Попробуйте закоментировать эту строку следующим образом (добавив в начало двойные кавычки):
"let g:airline_theme='solarized'
и проверить, остается ли ошибка.

**Comment by dar1ock** [comment]
пробовал. результат = 0.
при запуске vim цвета абы какие, причем пробовал уже ручную установку темы
и раз через раз ругается на не найденные привязки 

при запуске evim solarized запускается вполне нормально и с airline проблем нет, но редактор постоянно находится в режиме правки

**Comment by Bashka** [comment]
Я попробовал установить у себя эту цветовую схему. Все прошло нормально. Правда в консольной версии редактора (каковой я бользуюсь) текст сливается с фоном, но тема загружается и работает без проблем.

Еще я заметил, что у вас в .vim/plugins.vim дважды присутствует объявление плагина vim_start. Удалите одно из объявлений. Плагин vim_plugmanager не удаляет эти объявления из файла при удалении плагина, делать это необходимо вручную.

Пока я не могу сказать, с чем может быть связана эта ошибка.

**Comment by dar1ock** [comment]
видимо ошибка была вызвана очередностью загрузки плагинов.
сейчас прошел все с 0, поэтапно.
первыми поставил vim_lib и vim_plugmanager
затем airline, gitguter, nrdtree, vim_prj, vim_start ...
все работает. спасибо

**Comment by Bashka** [comment]
Возможно связано с очередью загрузки.
Да не за что.
